apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-webapp
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
      - image: barrydobson/sa-webapp
        imagePullPolicy: Always
        name: sa-webapp
        env:
          - name: SA_LOGIC_URL
            value: "http://sa-logic"
        ports:
          - containerPort: 80