#!/usr/bin/env bash

docker build -t barrydobson/sa-frontend:"$1" --build-arg WEB_APP_URL=$2 ../sa-frontend
docker build -t barrydobson/sa-webapp-java:"$1" ../sa-webapp-java
docker build -t barrydobson/sa-logic:"$1" ../sa-logic

docker push barrydobson/sa-frontend:"$1"
docker push barrydobson/sa-webapp-java:"$1"
docker push barrydobson/sa-logic:"$1"