version: "3"
services:
  sa-logic:
    build:
      context: ../sa-logic
    image: barrydobson/sa-logic
    ports:
      - "5050:5000"
  sa-webapp:
    build:
      context: ../sa-webapp
    image: barrydobson/sa-webapp
    ports:
      - "5051:80"
    environment:
      SA_LOGIC_URL: http://sa-logic:5000
    depends_on:
      - sa-logic
  sa-frontend:
    build:
      context: ../sa-frontend
    image: barrydobson/sa-frontend
    ports:
      - "5052:80"
    depends_on:
      - sa-webapp