apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kube-demo
  region: eu-west-2
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system