apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/frontend
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: Service
  metadata:
    name: sa-frontend-lb
  spec:
    type: NodePort
images:
  - name: barrydobson/sa-frontend
    newTag: aws-alb-2