apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/webapp
- alb-ingress.yaml
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: Service
  metadata:
    name: sa-webapp-lb
  spec:
    type: NodePort
